name: Build

on:
  push:
    branches:
      - "main"
      # - "images-ci"

jobs:
  build:
    continue-on-error: true

    strategy:
      matrix:
        include:
          - release_for: Linux-GNU-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            args: "--locked --release"

          - release_for: Linux-GNU-armv7
            os: ubuntu-20.04
            target: "armv7-unknown-linux-gnueabihf"
            args: "--locked --release --features vendored-openssl"

          # - release_for: Windows-x86_64
          #   os: windows-latest
          #   target: x86_64-pc-windows-msvc
          #   bin: controller.exe
          #   name: precious-Windows-x86_64.zip
          #   command: both

          # - release_for: macOS-x86_64
          #   os: macOS-latest
          #   target: x86_64-apple-darwin
          #   bin: controller
          #   name: precious-Darwin-x86_64.tar.gz
          #   command: both

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: both
          target: ${{ matrix.target }}
          args: ${{ matrix.args }}
          strip: true
