name: Release

on:
  push:
    tags: v*

jobs:
  build:
    continue-on-error: true

    strategy:
      matrix:
        include:
          - release_for: Linux-GNU-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            arch: amd64
            args: "--locked --release"

          - release_for: Linux-GNU-armv7
            os: ubuntu-latest
            target: "aarch64-unknown-linux-gnu"
            arch: arm64
            args: "--locked --release"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: both
          target: ${{ matrix.target }}
          args: ${{ matrix.args }}
          strip: true

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dmtrd-${{ matrix.arch }}
          path: target/${{ matrix.target }}/release/dmtrd

  docker:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/demeter-run/daemon
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{version}}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io/demeter-run
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .github/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
